title: indetail dev blog
description: Sporadic details on compilers, code and tooling from the world of LLVM
author: Stefan Gr√§nitz
url: https://weliveindetail.github.io
baseurl: "/blog"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
