title: weliveindetail dev blog
email: stefan.graenitz@gmail.com
description: >
  Details on compilers, debuggers, optimization- and instrumentation 
  tools from the world of LLVM
url: https://weliveindetail.github.io
baseurl: "/blog"
twitter_username: weliveindetail
github_username:  weliveindetail
linkedin_username: stefan-gr√§nitz-254298113

# Build settings
markdown: kramdown
theme: minima
pulgins:
  - jekyll-feed
  - jekyll-email-protect

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
